public with sharing class ConstantsPicklistValues {
    //Picklist static variable format -> Object_FieldName_Value. For eg. PLANT_ASSET_ASSET_BUILDER_STATUS_COMPLETED
    public final static String PLANT_ASSET_ASSET_BUILDER_STATUS_COMPLETED = 'Completed';
    public final static String PLANT_ASSET_ASSET_BUILDER_STATUS_IN_PROGRESS = 'In-Progress';
    public final static String PLANT_ASSET_ASSET_BUILDER_STATUS_CLOSED = 'Closed';
    public final static String PLANT_ASSET_PROMPT_DETAIL_REPORT_STATUS_IN_PROGRESS = 'In Progress';
    public final static String PLANT_ASSET_PROMPT_DETAIL_REPORT_STATUS_COMPLETED = 'Completed';
    public final static String PLANT_ASSET_PROMPT_DETAIL_REPORT_STATUS_COMPLETED_ERROR = 'Completed - Error';
}